services:
  - type: web
    name: fastapi-app       # Change this to your preferred service name
    env: python
    pythonVersion: 3.11
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host 192.168.31.179 --port 7000
